#!/opt/homebrew/bin/perl
use strict;
use warnings;
use cyclic_chain_polytopes;

while (<STDIN>) {
  printf "What is n?\n";
	chomp(read $n);
	printf "What are the (maximal) chains?\n";
	my @arr;
	my $count = 0;
	foreach my $line ( <STDIN> ) {
    chomp($line);
    push(@arr[$count], [$line]);
		$count++;
	}
print chains_to_polytope1(@arr) "\n";
print chains_to_polytope2(@arr);

1;
