#!/opt/homebrew/bin/perl
. playground
. cyclic_chain_polytopes

use strict
use warnings

while (<STDIN>) {
  printf "What is n?\n";
	chomp(read $n);
	printf "What are the (maximal) chains?\n";
	my @arr;
	my $count = 0;
	foreach my $line ( <STDIN> ) {
    chomp($line);
    push(@arr[$count], [$line]);
		$count++;
	}
print chains_to_polytope1(@arr) "\n";
print chains_to_polytope2(@arr);
